# -*- coding: utf-8 -*-
"""plot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMDnfNGy3kDhUTucUc0tle_ImmQuV85M
"""

Note: plot_solutions() requires MLP and KINN classes from train.py.
# All other plot functions work standalone using the CSV files in results/

import math
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch

OUT  = Path('results')
FIGS = OUT / 'figures'
FIGS.mkdir(exist_ok=True)

plt.rcParams.update({
    'font.family':    'serif',
    'font.size':      11,
    'axes.titlesize': 12,
    'axes.labelsize': 11,
    'legend.fontsize': 9,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
    'figure.dpi':     150,
    'savefig.dpi':    300,
    'savefig.bbox':   'tight',
    'axes.grid':      True,
    'grid.alpha':     0.3,
})

COLORS = {
    'MLP_fixed':     '#2196F3',
    'MLP_adaptive':  '#03A9F4',
    'KINN_fixed':    '#F44336',
    'KINN_adaptive': '#FF5722',
}

DRIVE_FIGS = Path('/content/drive/MyDrive/cs_810_project/figures')


def fmt(val):

    if np.isnan(val):
        return 'N/A'
    return f'{val:.4f}'


def save(fig, name):

    local = FIGS / name
    fig.savefig(local, dpi=300, bbox_inches='tight')
    try:
        DRIVE_FIGS.mkdir(parents=True, exist_ok=True)
        fig.savefig(DRIVE_FIGS / name, dpi=300, bbox_inches='tight')
    except Exception:
        pass
    plt.show()
    plt.close(fig)
    print(f'Saved: {name}')


def _load(fname):

    p = OUT / fname
    if not p.exists():
        print(f'  [missing] {fname}')
        return None
    return pd.read_csv(p)



# Convection β-sweep


def plot_beta_sweep():
    df = _load('convection_beta_sweep.csv')
    if df is None:
        return

    fig, ax = plt.subplots(figsize=(7, 4.5))

    plots = [
        ('MLP',  None, False, 'o-',  COLORS['MLP_fixed'],    'MLP (fixed)'),
        ('MLP',  None, True,  's--', COLORS['MLP_adaptive'],  'MLP (adaptive)'),
        ('KINN', 5,    False, '^-',  '#4CAF50',               'KINN gs=5 (fixed)'),
        ('KINN', 10,   False, 'D-',  COLORS['KINN_fixed'],    'KINN gs=10 (fixed)'),
        ('KINN', 20,   False, 'v-',  '#9C27B0',               'KINN gs=20 (fixed)'),
        ('KINN', 20,   True,  'P--', COLORS['KINN_adaptive'], 'KINN gs=20 (adaptive)'),
    ]

    for mtype, gs, aw, marker, color, label in plots:
        sub = df[(df['model'] == mtype) & (df['adaptive'] == aw)]
        if gs is not None:
            sub = sub[sub['grid_size'] == gs]
        else:
            sub = sub[sub['grid_size'].isna() | (sub['grid_size'].astype(str) == 'None')]
        if sub.empty:
            continue
        sub = sub.sort_values('beta')
        ax.semilogy(sub['beta'], sub['best_l2'], marker,
                    color=color, label=label, linewidth=2, markersize=7)

    ax.set_xlabel('Convection speed β')
    ax.set_ylabel('Relative L₂ error')
    ax.set_title('1D Convection: MLP-PINN vs KINN across β values')
    ax.legend(loc='upper left', fontsize=8)
    ax.set_xticks([1, 10, 30, 50])
    save(fig, 'fig1_beta_sweep.png')



def plot_heatmap():
    df = _load('convection_heatmap.csv')
    if df is None:
        return

    pivot = df.pivot(index='beta', columns='grid_size', values='best_l2')
    pivot = pivot.sort_index(ascending=False)

    #load MLP baselines
    conv  = _load('convection_beta_sweep.csv')
    mlp_ref = {}
    if conv is not None:
        mlp_sub = conv[(conv['model'] == 'MLP') & (conv['adaptive'] == False)]
        for _, row in mlp_sub.iterrows():
            mlp_ref[int(row['beta'])] = row['best_l2']

    fig, ax = plt.subplots(figsize=(8, 5))

    log_data = np.log10(pivot.values.astype(float))
    vmin, vmax = log_data.min(), log_data.max()

    im = ax.imshow(log_data, cmap='RdYlGn_r', aspect='auto', vmin=vmin, vmax=vmax)

    for i in range(log_data.shape[0]):
        for j in range(log_data.shape[1]):
            val = pivot.values[i, j]
            text_color = 'white' if log_data[i, j] > (vmin + vmax) / 2 else 'black'
            ax.text(j, i, fmt(val), ha='center', va='center',
                    fontsize=9, color=text_color, fontweight='bold')

    ax.set_xticks(range(len(pivot.columns)))
    ax.set_xticklabels([f'gs={g}' for g in pivot.columns])
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels([f'β={b}' for b in pivot.index])
    ax.set_xlabel('KAN Grid Size')
    ax.set_ylabel('Convection Speed β')
    ax.set_title('KINN: Relative L₂ Error — Grid Size × β\n(green = accurate, red = failure)')

    # MLP values below x-axis
    if mlp_ref:
        mlp_text = 'MLP baseline: ' + '   '.join(
            [f'β={b}: {fmt(v)}' for b, v in sorted(mlp_ref.items(), reverse=True)]
        )
        ax.set_xlabel(f'KAN Grid Size\n\n{mlp_text}', fontsize=9)

    cbar = plt.colorbar(im, ax=ax)
    cbar.set_label('log₁₀(L₂ error)')
    save(fig, 'fig2_heatmap.png')


# Loss decomposition at β=30


def plot_loss_decomp():
    df = _load('convection_loss_decomp.csv')
    if df is None:
        return

    df30 = df[df['beta'] == 30].copy()
    if df30.empty:
        print('  [missing] No β=30 data in loss_decomp CSV')
        return

    configs = [
        ('MLP',  False, COLORS['MLP_fixed'],    'MLP fixed'),
        ('MLP',  True,  COLORS['MLP_adaptive'], 'MLP adaptive'),
        ('KINN', False, COLORS['KINN_fixed'],    'KINN gs=20 fixed'),
        ('KINN', True,  COLORS['KINN_adaptive'], 'KINN gs=20 adaptive'),
    ]

    fig, axes = plt.subplots(1, 3, figsize=(13, 4), sharey=False)
    loss_keys = [('pde', 'PDE Residual'), ('ic', 'IC Loss'), ('bc', 'BC Loss')]

    for ax, (lkey, ltitle) in zip(axes, loss_keys):
        for mtype, aw, color, label in configs:
            sub = df30[(df30['model'] == mtype) & (df30['adaptive'] == aw)]
            if sub.empty:
                continue
            adam_sub  = sub[sub['phase'] == 'adam']
            lbfgs_sub = sub[sub['phase'] == 'lbfgs']
            if not adam_sub.empty:
                ax.semilogy(adam_sub['epoch'], adam_sub[lkey],
                            color=color, linewidth=1.5, label=label)
            if not lbfgs_sub.empty:
                ax.semilogy(lbfgs_sub['epoch'], lbfgs_sub[lkey],
                            color=color, linewidth=1.5, linestyle='--')
        ax.set_title(ltitle)
        ax.set_xlabel('Epoch')
        ax.axvline(x=8000, color='gray', linestyle=':', alpha=0.7)
        if ax == axes[0]:
            ax.set_ylabel('Loss value')

    axes[0].legend(fontsize=8, loc='upper right')
    fig.suptitle('Loss Decomposition at β=30  (solid=Adam, dashed=L-BFGS)', y=1.02)
    plt.tight_layout()
    save(fig, 'fig3_loss_decomp.png')


# Helmholtz frequency sweep

def plot_helmholtz_sweep():
    df = _load('helmholtz_freq_sweep.csv')
    if df is None:
        return

    fig, ax = plt.subplots(figsize=(7, 4.5))

    styles = [
        ('MLP',  None, False, 'o-',  COLORS['MLP_fixed'],    'MLP (fixed)'),
        ('MLP',  None, True,  's--', COLORS['MLP_adaptive'],  'MLP (adaptive)'),
        ('KINN', 10,   False, '^-',  COLORS['KINN_fixed'],    'KINN gs=10 (fixed)'),
        ('KINN', 10,   True,  'D--', COLORS['KINN_adaptive'], 'KINN gs=10 (adaptive)'),
        ('KINN', 30,   False, 'v-',  '#9C27B0',               'KINN gs=30 (fixed)'),
        ('KINN', 30,   True,  'P--', '#E91E63',               'KINN gs=30 (adaptive)'),
    ]

    for mtype, gs, aw, marker, color, label in styles:
        sub = df[(df['model'] == mtype) & (df['adaptive'] == aw)]
        if gs is not None:
            sub = sub[sub['grid_size'] == gs]
        else:
            sub = sub[sub['grid_size'].isna() | (sub['grid_size'].astype(str) == 'None')]
        if sub.empty:
            continue
        sub = sub.sort_values('n')
        ax.semilogy(sub['n'], sub['best_l2'], marker,
                    color=color, label=label, linewidth=2, markersize=7)

    ax.set_xlabel('Solution frequency n')
    ax.set_ylabel('Relative L₂ error')
    ax.set_title('2D Helmholtz: MLP-PINN vs KINN across frequencies')
    ax.set_xticks([1, 4, 8])
    ax.legend(loc='upper left', fontsize=8)
    save(fig, 'fig4_helmholtz_sweep.png')



# Parameter efficiency (all β values)


def plot_param_efficiency():
    dfs = []

    for beta in [1, 10, 30, 50]:
        path = OUT / f'param_efficiency_beta{beta}.csv'
        if path.exists():
            temp = pd.read_csv(path)
            if not temp.empty and len(temp) > 2:
                temp['beta'] = beta
                dfs.append(temp)
                continue

        # Fallback
        conv = _load('convection_beta_sweep.csv')
        if conv is not None:
            sub = conv[conv['beta'] == beta][['model', 'n_params', 'best_l2', 'adaptive']].copy()
            sub = sub[sub['adaptive'] == False].copy()
            if not sub.empty:
                sub['depth']        = sub['model'].apply(lambda x: 4 if x == 'MLP' else 2)
                sub['width']        = sub['model'].apply(lambda x: 128 if x == 'MLP' else 5)
                sub['grid_size']    = sub['model'].apply(lambda x: None if x == 'MLP' else 10)
                sub['beta']         = beta
                sub['train_time_s'] = 0
                dfs.append(sub)

    if not dfs:
        print('  [missing] No param efficiency data found')
        return

    df = pd.concat(dfs, ignore_index=True)

    fig, axes = plt.subplots(1, 4, figsize=(16, 4.5), sharey=False)

    for ax, beta in zip(axes, [1, 10, 30, 50]):
        sub  = df[df['beta'] == beta]
        mlp  = sub[sub['model'] == 'MLP']
        kinn = sub[sub['model'] == 'KINN']

        if sub.empty:
            ax.text(0.5, 0.5, 'No data', ha='center', va='center',
                    transform=ax.transAxes)
        else:
            if not mlp.empty:
                ax.scatter(mlp['n_params'], mlp['best_l2'],
                           color=COLORS['MLP_fixed'], s=80, marker='o',
                           label='MLP', zorder=5, edgecolors='white', linewidths=0.5)
            if not kinn.empty:
                ax.scatter(kinn['n_params'], kinn['best_l2'],
                           color=COLORS['KINN_fixed'], s=80, marker='^',
                           label='KINN', zorder=5, edgecolors='white', linewidths=0.5)
            ax.set_xscale('log')
            ax.set_yscale('log')
            ax.legend(fontsize=8)

        ax.set_title(f'β={beta}')
        ax.set_xlabel('Parameters')
        ax.grid(True, alpha=0.3)
        if ax == axes[0]:
            ax.set_ylabel('Relative L₂ error')

    fig.suptitle('Parameter Efficiency: L₂ Error vs Model Size across β values',
                 fontsize=12, y=1.02)
    plt.tight_layout()
    save(fig, 'fig5_param_efficiency.png')


#Convection solution plots (exact vs MLP vs KINN)


def plot_solutions(beta=30):
    LB = [0., 0.]; UB = [2 * math.pi, 1.]
    xv = torch.linspace(0, 2 * math.pi, 256)
    tv = torch.linspace(0, 1, 256)
    X, T   = torch.meshgrid(xv, tv, indexing='ij')
    coords = torch.cat([X.reshape(-1,1), T.reshape(-1,1)], 1).to(device)
    u_exact = torch.sin(coords[:,0:1] - beta * coords[:,1:2]).cpu().numpy().reshape(256, 256)

    fig, axes = plt.subplots(1, 3, figsize=(13, 4))
    vmin, vmax = -1.0, 1.0

    im = axes[0].imshow(u_exact, extent=[0,1,0,2*math.pi],
                        aspect='auto', origin='lower', cmap='RdBu_r',
                        vmin=vmin, vmax=vmax)
    axes[0].set_title('Exact solution')
    axes[0].set_xlabel('t'); axes[0].set_ylabel('x')
    plt.colorbar(im, ax=axes[0])

    # MLP
    mlp_key  = f'aw=False_beta={beta}_model=MLP_pde=conv'
    mlp_path = OUT / f'weights_{mlp_key}.pt'
    if mlp_path.exists():
        mlp = MLP(2, MLP_DEPTH, MLP_WIDTH, MLP_ACT, lb=LB, ub=UB).to(device)
        mlp.load_state_dict(torch.load(mlp_path, map_location=device))
        mlp.eval()
        with torch.no_grad():
            u_mlp = mlp(coords).cpu().numpy().reshape(256, 256)
        l2  = np.sqrt(np.mean((u_mlp-u_exact)**2)) / np.sqrt(np.mean(u_exact**2))
        im2 = axes[1].imshow(u_mlp, extent=[0,1,0,2*math.pi],
                             aspect='auto', origin='lower', cmap='RdBu_r',
                             vmin=vmin, vmax=vmax)
        axes[1].set_title(f'MLP-PINN  (L₂={fmt(l2)})')
        axes[1].set_xlabel('t'); axes[1].set_ylabel('x')
        plt.colorbar(im2, ax=axes[1])
    else:
        axes[1].text(0.5, 0.5, 'weights not found', ha='center', va='center',
                     transform=axes[1].transAxes, fontsize=9)

    # KINN gs=10
    kinn_key  = f'aw = False_beta = {beta}_gs = 10_model= KINN_pde = conv'
    kinn_path = OUT / f'weights_{kinn_key}.pt'
    if kinn_path.exists():
        kan = KINN(2, KAN_HIDDEN_W, KAN_N_HIDDEN, 10, lb=LB, ub=UB).to(device)
        kan.load_state_dict(torch.load(kinn_path, map_location=device))
        kan.eval()
        with torch.no_grad():
            u_kinn = kan(coords).cpu().numpy().reshape(256, 256)
        l2   = np.sqrt(np.mean((u_kinn-u_exact)**2)) / np.sqrt(np.mean(u_exact**2))
        im3  = axes[2].imshow(u_kinn, extent=[0,1,0,2*math.pi],
                              aspect='auto', origin='lower', cmap='RdBu_r',
                              vmin=vmin, vmax=vmax)
        axes[2].set_title(f'KINN gs=10  (L₂={fmt(l2)})')
        axes[2].set_xlabel('t'); axes[2].set_ylabel('x')
        plt.colorbar(im3, ax=axes[2])
    else:
        axes[2].text(0.5, 0.5, 'weights not found', ha='center', va='center',
                     transform=axes[2].transAxes, fontsize=9)

    fig.suptitle(f'Convection solution comparison  β={beta}', y=1.02)
    plt.tight_layout()
    save(fig, f'fig6_solution_beta{beta}.png')

# Summary table


def plot_summary_table():
    conv = _load('convection_beta_sweep.csv')
    if conv is None:
        return

    rows = []
    for beta in [1, 10, 30, 50]:
        mlp_f = conv[(conv['model']=='MLP') & (~conv['adaptive']) & (conv['beta']==beta)]['best_l2'].values
        mlp_a = conv[(conv['model']=='MLP') & (conv['adaptive'])  & (conv['beta']==beta)]['best_l2'].values
        kinn  = conv[(conv['model']=='KINN') & (~conv['adaptive']) & (conv['beta']==beta)]['best_l2']
        rows.append({
            'β':           beta,
            'MLP fixed':   mlp_f[0] if len(mlp_f) > 0 else np.nan,
            'MLP adaptive':mlp_a[0] if len(mlp_a) > 0 else np.nan,
            'KINN best':   kinn.min() if not kinn.empty else np.nan,
        })

    df_s = pd.DataFrame(rows)
    fig, ax = plt.subplots(figsize=(9, 3))
    ax.axis('off')

    table_data = []
    for _, row in df_s.iterrows():
        table_data.append([
            f"β={int(row['β'])}",
            fmt(row['MLP fixed']),
            fmt(row['MLP adaptive']),
            fmt(row['KINN best']),
        ])

    tbl = ax.table(
        cellText=table_data,
        colLabels=['β', 'MLP (fixed)', 'MLP (adaptive)', 'KINN (best grid)'],
        cellLoc='center', loc='center',
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(11)
    tbl.scale(1.2, 2.0)

    for (row, col), cell in tbl.get_celld().items():
        if row == 0:
            cell.set_facecolor('#37474F')
            cell.set_text_props(color='white', fontweight='bold')
        elif col > 0:
            try:
                val = float(cell.get_text().get_text())
                if val > 0.1:
                    cell.set_facecolor('#FFCDD2')
                elif val < 0.01:
                    cell.set_facecolor('#C8E6C9')
                else:
                    cell.set_facecolor('#FFF9C4')
            except ValueError:
                pass

    ax.set_title('Convection: Relative L₂ Error  (green < 0.01 | yellow 0.01–0.1 | red > 0.1)',
                 pad=20, fontsize=11)
    save(fig, 'fig7_summary_table.png')



#Helmholtz summary table


def plot_helmholtz_table():
    df = _load('helmholtz_freq_sweep.csv')
    if df is None:
        return

    fig, ax = plt.subplots(figsize=(10, 3.5))
    ax.axis('off')

    table_data = []
    for n in [1, 4, 8]:
        mlp_f  = df[(df['model']=='MLP')  & (~df['adaptive']) & (df['n']==n)]['best_l2'].values
        mlp_a  = df[(df['model']=='MLP')  & (df['adaptive'])  & (df['n']==n)]['best_l2'].values
        k10_f  = df[(df['model']=='KINN') & (~df['adaptive']) & (df['n']==n) & (df['grid_size']==10)]['best_l2'].values
        k10_a  = df[(df['model']=='KINN') & (df['adaptive'])  & (df['n']==n) & (df['grid_size']==10)]['best_l2'].values
        k30_f  = df[(df['model']=='KINN') & (~df['adaptive']) & (df['n']==n) & (df['grid_size']==30)]['best_l2'].values
        k30_a  = df[(df['model']=='KINN') & (df['adaptive'])  & (df['n']==n) & (df['grid_size']==30)]['best_l2'].values
        table_data.append([
            f'n={n}',
            fmt(mlp_f[0])  if len(mlp_f)  > 0 else 'N/A',
            fmt(mlp_a[0])  if len(mlp_a)  > 0 else 'N/A',
            fmt(k10_f[0])  if len(k10_f)  > 0 else 'N/A',
            fmt(k10_a[0])  if len(k10_a)  > 0 else 'N/A',
            fmt(k30_f[0])  if len(k30_f)  > 0 else 'N/A',
            fmt(k30_a[0])  if len(k30_a)  > 0 else 'N/A',
        ])

    tbl = ax.table(
        cellText=table_data,
        colLabels=['n', 'MLP fixed', 'MLP adaptive',
                   'KINN gs=10 fixed', 'KINN gs=10 adaptive',
                   'KINN gs=30 fixed', 'KINN gs=30 adaptive'],
        cellLoc='center', loc='center',
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(9)
    tbl.scale(1.1, 2.0)

    for (row, col), cell in tbl.get_celld().items():
        if row == 0:
            cell.set_facecolor('#37474F')
            cell.set_text_props(color='white', fontweight='bold')
        elif col > 0:
            try:
                val = float(cell.get_text().get_text())
                if val > 0.1:
                    cell.set_facecolor('#FFCDD2')
                elif val < 0.01:
                    cell.set_facecolor('#C8E6C9')
                else:
                    cell.set_facecolor('#FFF9C4')
            except ValueError:
                pass

    ax.set_title('Helmholtz: Relative L₂ Error  (green < 0.01 | yellow 0.01–0.1 | red > 0.1)',
                 pad=20, fontsize=11)
    save(fig, 'fig9_helmholtz_table.png')



# run all


def run_all():
    print('Generating all figures...\n')
    fns = [
        ('Beta sweep',              plot_beta_sweep),
        ('Grid heatmap',            plot_heatmap),
        ('Loss decomposition',      plot_loss_decomp),
        ('Helmholtz sweep',         plot_helmholtz_sweep),
        ('Parameter efficiency',    plot_param_efficiency),
        ('Solution β=1',            lambda: plot_solutions(beta=1)),
        ('Solution β=10',           lambda: plot_solutions(beta=10)),
        ('Solution β=30',           lambda: plot_solutions(beta=30)),
        ('Solution β=50',           lambda: plot_solutions(beta=50)),
        ('Summary table',           plot_summary_table),
        ('Helmholtz solutions n=8', lambda: plot_helmholtz_solutions(n=8)),
        ('Helmholtz table',         plot_helmholtz_table),
    ]
    for name, fn in fns:
        try:
            fn()
        except FileNotFoundError as e:
            print(f'  SKIP {name} — {e}')
        except Exception as e:
            print(f'  ERROR {name} — {e}')

    print(f'\nAll figures saved to {FIGS}/')
    for p in sorted(FIGS.glob('*.png')):
        print(f'  {p.name}')

run_all()