# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKx9M10RU2LKWH7PdYu7VBKGOC0b_6sr
"""

import math
import shutil
import time
import warnings
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional, Set

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch import Tensor
from tqdm.notebook import tqdm

warnings.filterwarnings('ignore')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

OUT = Path('results')
OUT.mkdir(exist_ok=True)

drive_root       = Path('/content/drive/MyDrive/cs_810_project')
drive_checkpoint = drive_root / 'mid_checkpoint'
drive_results    = drive_root / 'results'
drive_done_csv   = drive_root / 'completed_runs.csv'

CKPT_EPOCHS = 1_000
CKPT_LBFGS  = 50

MLP_DEPTH = 4
MLP_WIDTH = 128
MLP_ACT   = 'tanh'

KAN_HIDDEN_W = 5
KAN_N_HIDDEN = 2
KAN_SPLINE_K = 3

CONV_BETAS = [1, 10, 30, 50]
HELM_FREQS = [1, 4, 8]
KAN_GRIDS  = [5, 10, 20, 50]

N_INT_CONV = 50_000
N_INT_HELM = 50_000
N_INT_POIS = 10_000
N_IC       = 500
N_BC_EDGE  = 500
N_VAL      = 256

ADAM_LR     = 1e-3
ADAM_EPOCHS = 10_000
LBFGS_OUTER = 200
EARLY_PAT   = 5_000
LOG_EVERY   = 100

def make_run_key(**kwargs) -> str:

    return '_'.join(f'{k}={v}' for k, v in sorted(kwargs.items()))


class DriveCheckpoint:
    def __init__(self):
        self.available = Path('/content/drive/MyDrive').exists()

        if self.available:
            drive_checkpoint.mkdir(parents=True, exist_ok=True)
            drive_results.mkdir(parents=True, exist_ok=True)

        self._done: Set[str] = set()
        if self.available and drive_done_csv.exists():
            try:
                df = pd.read_csv(drive_done_csv)
                if 'run_key' in df.columns:
                    self._done = set(df['run_key'].astype(str).tolist())
            except Exception:
                pass

    def is_done(self, run_key: str) -> bool:
        return run_key in self._done

    def mark_done(self, run_key: str, meta: Dict) -> None:
        self._done.add(run_key)
        if not self.available:
            return
        try:
            row    = {'run_key': run_key, 'ts': datetime.now().isoformat(), **meta}
            header = not drive_done_csv.exists()
            pd.DataFrame([row]).to_csv(drive_done_csv, mode='a', header=header, index=False)
        except Exception:
            pass

    def sync_csv(self, local_path: Path) -> None:
        if not self.available:
            return
        try:
            shutil.copy2(local_path, drive_results / local_path.name)
        except Exception:
            pass

    def save_mid(self, run_key: str, state: Dict) -> None:
        if not self.available:
            return
        try:
            torch.save(state, drive_checkpoint / f'{run_key}.pt')
        except Exception:
            pass

    def load_mid(self, run_key: str) -> Optional[Dict]:
        if not self.available:
            return None
        path = drive_checkpoint / f'{run_key}.pt'
        if not path.exists():
            return None
        try:
            return torch.load(path, map_location=device)
        except Exception:
            return None

    def clear_mid(self, run_key: str) -> None:
        if not self.available:
            return
        try:
            (drive_checkpoint / f'{run_key}.pt').unlink(missing_ok=True)
        except Exception:
            pass

def count_params(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


class MLP(nn.Module):
    _ACTS = {'tanh': nn.Tanh, 'silu': nn.SiLU}

    def __init__(self, input_dim, depth, width, act,
                 lb=None, ub=None):
        super().__init__()
        assert act in self._ACTS
        _lb = torch.zeros(input_dim) if lb is None else torch.tensor(lb, dtype=torch.float32)
        _ub = torch.ones(input_dim)  if ub is None else torch.tensor(ub, dtype=torch.float32)
        self.register_buffer('lb', _lb)
        self.register_buffer('ub', _ub)
        act_cls = self._ACTS[act]
        layers = [nn.Linear(input_dim, width), act_cls()]
        for _ in range(depth - 1):
            layers += [nn.Linear(width, width), act_cls()]
        layers.append(nn.Linear(width, 1))
        self.net = nn.Sequential(*layers)
        for m in self.net.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)

    def _norm(self, c):
        return 2.0 * (c - self.lb) / (self.ub - self.lb + 1e-12) - 1.0

    def forward(self, coords):
        return self.net(self._norm(coords))


class KINN(nn.Module):
    """
    Three mandatory KINN modifications (Wang et al. 2024):
    1. Input normalised to [-1,1]^d — B-splines only valid in grid_range.
    2. tanh after every hidden layer — prevents derivative collapse (Appendix C).
    3. Spline order k=3 fixed — accuracy plateaus beyond this (Fig 8b).
    """

    def __init__(self, input_dim, hidden_w, n_hidden, grid_size,
                 spline_order=KAN_SPLINE_K, lb=None, ub=None):
        super().__init__()
        if not KAN_AVAILABLE:
            raise RuntimeError('KAN not installed?')
        _lb = torch.zeros(input_dim) if lb is None else torch.tensor(lb, dtype=torch.float32)
        _ub = torch.ones(input_dim)  if ub is None else torch.tensor(ub, dtype=torch.float32)
        self.register_buffer('lb', _lb)
        self.register_buffer('ub', _ub)
        dims = [input_dim] + [hidden_w] * n_hidden + [1]
        self.kan_layers = nn.ModuleList([
            KANLinear(
                in_features=dims[i], out_features=dims[i+1],
                grid_size=grid_size, spline_order=spline_order,
                scale_noise=0.1, scale_base=1.0, scale_spline=1.0,
                enable_standalone_scale_spline=True,
                base_activation=nn.SiLU,
                grid_eps=0.02, grid_range=[-1.0, 1.0],
            )
            for i in range(len(dims) - 1)
        ])
        self._n_hidden = n_hidden

    def _norm(self, c):
        return 2.0 * (c - self.lb) / (self.ub - self.lb + 1e-12) - 1.0

    def forward(self, coords):
        h = self._norm(coords)
        for i, layer in enumerate(self.kan_layers):
            h = layer(h)
            if i < self._n_hidden:
                h = torch.tanh(h)
        return h

def _d1(u, c):
    return torch.autograd.grad(u, c, grad_outputs=torch.ones_like(u), create_graph=True)[0]


# 1D Convection
def u_convection(x, t, beta):
    return torch.sin(x - beta * t)

def res_convection(model, coords_f, beta):
    c = coords_f.detach().clone().requires_grad_(True)
    u = model(c)
    g = torch.autograd.grad(u, c, grad_outputs=torch.ones_like(u), create_graph=True)[0]
    u_x, u_t = g[:, 0:1], g[:, 1:2]
    return torch.mean((u_t + beta * u_x) ** 2)

def make_convection_data(seed=0):
    g   = torch.Generator(); g.manual_seed(seed)
    x_f = torch.rand(N_INT_CONV, 1, generator=g) * 2 * math.pi
    t_f = torch.rand(N_INT_CONV, 1, generator=g)
    x_ic = torch.linspace(0, 2 * math.pi, N_IC).reshape(-1, 1)
    t_bc = torch.rand(N_BC_EDGE, 1, generator=g)
    xv, tv = torch.linspace(0, 2*math.pi, N_VAL), torch.linspace(0, 1, N_VAL)
    X, T   = torch.meshgrid(xv, tv, indexing='ij')
    d = {
        'coords_f':    torch.cat([x_f, t_f], 1),
        'coords_ic':   torch.cat([x_ic, torch.zeros_like(x_ic)], 1),
        'u_ic':        torch.sin(x_ic),
        'coords_bc_L': torch.cat([torch.zeros(N_BC_EDGE, 1), t_bc], 1),
        'coords_bc_R': torch.cat([torch.full((N_BC_EDGE, 1), 2*math.pi), t_bc], 1),
        'x_val': X.reshape(-1, 1),
        't_val': T.reshape(-1, 1),
    }
    return {k: v.to(device) for k, v in d.items()}

def compute_losses_convection(model, data, beta, weights=None):
    w     = weights or {'pde': 1., 'ic': 1., 'bc': 1.}
    pde_l = res_convection(model, data['coords_f'], beta)
    ic_l  = torch.mean((model(data['coords_ic']) - data['u_ic']) ** 2)
    bc_l  = torch.mean((model(data['coords_bc_L']) - model(data['coords_bc_R'])) ** 2)
    return w['pde']*pde_l + w['ic']*ic_l + w['bc']*bc_l, pde_l, ic_l, bc_l

@torch.no_grad()
def eval_convection(model, data, beta):
    model.eval()
    coords_v = torch.cat([data['x_val'], data['t_val']], 1)
    u_pred   = model(coords_v)
    u_true   = u_convection(data['x_val'], data['t_val'], beta)
    err = (torch.sqrt(torch.mean((u_pred - u_true)**2)) /
           (torch.sqrt(torch.mean(u_true**2)) + 1e-12)).item()
    model.train(); return err


# 2D Helmholtz
def u_helmholtz(x, y, n):
    return torch.sin(n * math.pi * x) * torch.sin(n * math.pi * y)

def res_helmholtz(model, coords_f, n, k=1.0):
    c    = coords_f.detach().clone().requires_grad_(True)
    u    = model(c)
    x, y = c[:, 0:1], c[:, 1:2]
    g1   = torch.autograd.grad(u, c, grad_outputs=torch.ones_like(u), create_graph=True)[0]
    u_x, u_y = g1[:, 0:1], g1[:, 1:2]
    u_xx = _d1(u_x, c)[:, 0:1]
    u_yy = _d1(u_y, c)[:, 1:2]
    f    = (k**2 - 2*(n*math.pi)**2) * torch.sin(n*math.pi*x) * torch.sin(n*math.pi*y)
    return torch.mean((u_xx + u_yy + k**2 * u - f) ** 2)

def make_helmholtz_data(seed=0):
    g   = torch.Generator(); g.manual_seed(seed)
    x_f = torch.rand(N_INT_HELM, 1, generator=g) * 2 - 1
    y_f = torch.rand(N_INT_HELM, 1, generator=g) * 2 - 1
    e   = torch.rand(N_BC_EDGE, 1, generator=g) * 2 - 1
    o, mo = torch.ones(N_BC_EDGE, 1), -torch.ones(N_BC_EDGE, 1)
    xv, yv = torch.linspace(-1, 1, N_VAL), torch.linspace(-1, 1, N_VAL)
    X, Y   = torch.meshgrid(xv, yv, indexing='ij')
    d = {
        'coords_f':  torch.cat([x_f, y_f], 1),
        'coords_bc': torch.cat([
            torch.cat([e, o], 1), torch.cat([e, mo], 1),
            torch.cat([o, e], 1), torch.cat([mo, e], 1)
        ], 0),
        'x_val': X.reshape(-1, 1),
        'y_val': Y.reshape(-1, 1),
    }
    return {k: v.to(device) for k, v in d.items()}

def compute_losses_helmholtz(model, data, n, k=1.0, weights=None):
    w     = weights or {'pde': 1., 'bc': 1.}
    pde_l = res_helmholtz(model, data['coords_f'], n, k)
    bc_l  = torch.mean(model(data['coords_bc']) ** 2)
    ic_l  = torch.tensor(0., device=device)
    return w['pde']*pde_l + w['bc']*bc_l, pde_l, ic_l, bc_l

@torch.no_grad()
def eval_helmholtz(model, data, n):
    model.eval()
    coords_v = torch.cat([data['x_val'], data['y_val']], 1)
    u_pred   = model(coords_v)
    u_true   = u_helmholtz(data['x_val'], data['y_val'], n)
    err = (torch.sqrt(torch.mean((u_pred - u_true)**2)) /
           (torch.sqrt(torch.mean(u_true**2)) + 1e-12)).item()
    model.train(); return err


# 1D Multi-scale Poisson
def u_poisson_ms(x):
    return torch.sin(2 * math.pi * x) + 0.1 * torch.sin(50 * math.pi * x)

def res_poisson_ms(model, coords_f):
    c    = coords_f.detach().clone().requires_grad_(True)
    u    = model(c)
    u_x  = _d1(u, c)
    u_xx = _d1(u_x, c)
    f    = (4*math.pi**2 * torch.sin(2*math.pi*c) +
            250*math.pi**2 * torch.sin(50*math.pi*c))
    return torch.mean((-u_xx - f) ** 2)

def make_poisson_data(seed=0):
    g    = torch.Generator(); g.manual_seed(seed)
    x_f  = torch.rand(N_INT_POIS, 1, generator=g)
    x_bc = torch.tensor([[0.0], [1.0]])
    d = {
        'x_f':   x_f,
        'x_bc':  x_bc,
        'u_bc':  u_poisson_ms(x_bc),
        'x_val': torch.linspace(0, 1, N_VAL).reshape(-1, 1),
    }
    return {k: v.to(device) for k, v in d.items()}

def compute_losses_poisson(model, data, weights=None):
    w     = weights or {'pde': 1., 'bc': 1.}
    pde_l = res_poisson_ms(model, data['x_f'])
    bc_l  = torch.mean((model(data['x_bc']) - data['u_bc']) ** 2)
    ic_l  = torch.tensor(0., device=device)
    return w['pde']*pde_l + w['bc']*bc_l, pde_l, ic_l, bc_l

@torch.no_grad()
def eval_poisson(model, data):
    model.eval()
    err = (torch.sqrt(torch.mean((model(data['x_val']) - u_poisson_ms(data['x_val']))**2)) /
           (torch.sqrt(torch.mean(u_poisson_ms(data['x_val'])**2)) + 1e-12)).item()
    model.train(); return err

class AdaptiveWeighter:
    def __init__(self, alpha=0.9, update_every=100, clip=(0.01, 100.)):
        self.alpha = alpha
        self.every = update_every
        self.clip  = clip
        self.w     = {'pde': 1., 'ic': 1., 'bc': 1.}
        self._step = 0

    def _max_grad(self, loss, model):
        gs   = torch.autograd.grad(loss, model.parameters(), retain_graph=True, allow_unused=True)
        vals = [g.abs().max().item() for g in gs if g is not None]
        return max(vals) if vals else 1.

    def _mean_grad(self, loss, model):
        gs   = torch.autograd.grad(loss, model.parameters(), retain_graph=True, allow_unused=True)
        vals = [g.abs().mean().item() for g in gs if g is not None]
        return float(np.mean(vals)) if vals else 1.

    def step(self, losses_fn, model):
        self._step += 1

        if self._step % self.every != 0:
            return
        model.zero_grad()
        _, pde_l, ic_l, bc_l = losses_fn()
        ref = self._max_grad(pde_l, model)
        if ic_l.item() > 0.:
            raw = ref / (self._mean_grad(ic_l, model) + 1e-12)
            self.w['ic'] = self.alpha*self.w['ic'] + (1-self.alpha)*float(np.clip(raw, *self.clip))
        raw = ref / (self._mean_grad(bc_l, model) + 1e-12)
        self.w['bc'] = self.alpha*self.w['bc'] + (1-self.alpha)*float(np.clip(raw, *self.clip))
        model.zero_grad()

    def get(self):             return dict(self.w)
    def state_dict(self):      return {'w': self.w, 'step': self._step}
    def load_state_dict(self, d): self.w = d['w']; self._step = d['step']


def train(model, losses_fn, eval_fn, run_key, checkpoint,
          label='', use_adaptive=False,
          adam_epochs=ADAM_EPOCHS, lbfgs_outer=LBFGS_OUTER,
          patience=EARLY_PAT, seed=0):

    torch.manual_seed(seed)


    optimizer = optim.Adam(model.parameters(), lr=ADAM_LR)
    scheduler = optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.9995)

    weighter    = AdaptiveWeighter() if use_adaptive else None
    best_l2     = float('inf')
    best_state  = None
    pat_ctr     = 0
    t0          = time.time()
    start_epoch = 0
    start_phase = 'adam'
    start_lbfgs = 0

    hist = {k: [] for k in
            ['epoch','total','pde','ic','bc','l2','w_pde','w_ic','w_bc','phase']}

    local_best = Path(f'/tmp/best_{run_key[:50]}.pt')

    #  Save optimizer and scheduler states
    def _pack_mid(epoch, phase, lbfgs_step=0):
        return {
            'model_state':      model.state_dict(),
            'optimizer_state':  optimizer.state_dict(),
            'scheduler_state':  scheduler.state_dict(),
            'best_model_state': best_state,
            'epoch':            epoch,
            'phase':            phase,
            'lbfgs_outer':      lbfgs_step,
            'best_l2':          best_l2,
            'patience_ctr':     pat_ctr,
            'history':          hist,
            'final_w':          weighter.get() if weighter else {'pde':1.,'ic':1.,'bc':1.},
            'weighter':         weighter.state_dict() if weighter else None,
        }

    # Restore states to prevent loss spikes
    mid = checkpoint.load_mid(run_key)
    if mid is not None:
        try:
            model.load_state_dict(mid['model_state'])
            if 'optimizer_state' in mid:
                optimizer.load_state_dict(mid['optimizer_state'])
            if 'scheduler_state' in mid:
                scheduler.load_state_dict(mid['scheduler_state'])

            best_l2     = mid['best_l2']
            best_state  = mid.get('best_model_state')
            pat_ctr     = mid.get('patience_ctr', 0)
            hist        = mid['history']
            start_phase = mid.get('phase', 'adam')
            start_epoch = mid.get('epoch', 0)
            start_lbfgs = mid.get('lbfgs_outer', 0)
            if weighter and mid.get('weighter'):
                weighter.load_state_dict(mid['weighter'])
        except Exception as e:
            print(f"Resume failed ({e}). Starting fresh.")
            mid = None

    def _log(epoch, total, pde_l, ic_l, bc_l, l2, ww, phase):
        for key, val in [
            ('epoch',epoch),('total',total.item()),('pde',pde_l.item()),
            ('ic',ic_l.item()),('bc',bc_l.item()),('l2',l2),
            ('w_pde',ww['pde']),('w_ic',ww['ic']),('w_bc',ww['bc']),
            ('phase',phase)
        ]:
            hist[key].append(val)

    already_done = start_epoch if start_phase == 'adam' else adam_epochs + start_lbfgs

    # Phase 1 — Adam
    adam_bar = tqdm(
        total=adam_epochs,
        desc=f'Adam  {label}',
        leave=True,

        dynamic_ncols=False,
        initial=start_epoch,
    )

    if start_phase == 'adam':
        model.train()
        for epoch in range(start_epoch + 1, adam_epochs + 1):
            optimizer.zero_grad()
            if weighter:
                weighter.step(lambda: losses_fn(None), model)
            w = weighter.get() if weighter else None
            total, pde_l, ic_l, bc_l = losses_fn(w)
            total.backward()

            #  Gradient Clipping Essential for high frequency / high beta stability
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()
            scheduler.step()
            adam_bar.update(1)

            if epoch % LOG_EVERY == 0:
                l2 = eval_fn()
                ww = w or {'pde':1.,'ic':1.,'bc':1.}
                _log(epoch, total, pde_l, ic_l, bc_l, l2, ww, 'adam')
                adam_bar.set_postfix(L2=f'{l2:.3e}', PDE=f'{pde_l.item():.2e}')
                if l2 < best_l2:
                    best_l2    = l2
                    best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                    pat_ctr    = 0
                    torch.save(model.state_dict(), local_best)
                else:
                    pat_ctr += LOG_EVERY
                    if pat_ctr >= patience:
                        adam_bar.update(adam_epochs - epoch)
                        break

            if epoch % CKPT_EPOCHS == 0:
                checkpoint.save_mid(run_key, _pack_mid(epoch, 'adam'))

        if local_best.exists():

            model.load_state_dict(torch.load(local_best, map_location=device))
            local_best.unlink()

    adam_bar.close()

    # Phase 2 — LBFGS
    w_lb = weighter.get() if weighter else {'pde':1.,'ic':1.,'bc':1.}

    opt_lb = optim.LBFGS(
        model.parameters(), lr=1.0, max_iter=50, max_eval=65,
        history_size=50, tolerance_grad=1e-8, tolerance_change=1e-10,
        line_search_fn='strong_wolfe',
    )

    lbfgs_bar = tqdm(
        total=lbfgs_outer,
        desc=f'LBFGS {label}',
        leave=True,

        dynamic_ncols=False,
        initial=start_lbfgs,
    )

    model.train()
    for outer in range(lbfgs_outer):
        if outer < start_lbfgs:
            continue

        def closure():
            opt_lb.zero_grad()
            tot, _, _, _ = losses_fn(w_lb)
            tot.backward()
            return tot

        try:
            opt_lb.step(closure)
        except RuntimeError:
            lbfgs_bar.update(lbfgs_outer - outer)
            break

        lbfgs_bar.update(1)

        if outer % 10 == 0:
            tot, pde_l, ic_l, bc_l = losses_fn(w_lb)
            l2 = eval_fn()


            _log(adam_epochs + outer, tot, pde_l, ic_l, bc_l, l2, w_lb, 'lbfgs')

            lbfgs_bar.set_postfix(L2=f'{l2:.3e}', PDE=f'{pde_l.item():.2e}')
            if l2 < best_l2:
                best_l2    = l2
                best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}

        if outer % CKPT_LBFGS == 0 and outer > 0:
            checkpoint.save_mid(run_key, _pack_mid(adam_epochs + outer, 'lbfgs', outer))

    lbfgs_bar.close()
    checkpoint.clear_mid(run_key)

    return {
        'history':          hist,
        'best_l2':          best_l2,
        'best_model_state': best_state,
        'n_params':         count_params(model),
        'train_time':       time.time() - t0,
        'final_w':          w_lb,
    }

def _save_data(data, path, checkpoint):
    cpu_data = {k: v.cpu() for k, v in data.items()}
    torch.save(cpu_data, path)
    checkpoint.sync_csv(path)

def _load_data(path):
    if not path.exists():
        return None
    return {k: v.to(device) for k, v in torch.load(path, map_location=device).items()}

def _save_weights(res, run_key, checkpoint):
    if res['best_model_state'] is None:
        return
    path = OUT / f'weights_{run_key}.pt'
    torch.save(res['best_model_state'], path)
    checkpoint.sync_csv(path)

def _append_history(rows, res, base):
    for i, ep in enumerate(res['history']['epoch']):
        rows.append({**base,
                     'epoch': ep, 'phase': res['history']['phase'][i],
                     'total': res['history']['total'][i],
                     'pde':   res['history']['pde'][i],
                     'ic':    res['history']['ic'][i],
                     'bc':    res['history']['bc'][i],
                     'l2':    res['history']['l2'][i],
                     'w_pde': res['history']['w_pde'][i],
                     'w_ic':  res['history']['w_ic'][i],
                     'w_bc':  res['history']['w_bc'][i]})

def _summary_row(base, res):
    return {**base, 'best_l2': res['best_l2'],
            'n_params': res['n_params'],
            'train_time_s': round(res['train_time'], 1)}

def _save(df, fname, checkpoint):
    p = OUT / fname
    df.to_csv(p, index=False)
    checkpoint.sync_csv(p)


def run_convection(checkpoint):
    LB = [0., 0.]; UB = [2*math.pi, 1.]
    sweep_rows = []; heatmap_rows = []; decomp_rows = []


    data_path = OUT / 'data_convection.pt'
    data = _load_data(data_path)
    if data is None:
        data = make_convection_data(seed=0)
        _save_data(data, data_path, checkpoint)

    for beta in tqdm(CONV_BETAS, desc='convection beta', colour='yellow'):

        for aw in [False, True]:
            rk = make_run_key(pde='conv', model='MLP', beta=beta, aw=aw)
            if checkpoint.is_done(rk):
                continue
            mlp = MLP(2, MLP_DEPTH, MLP_WIDTH, MLP_ACT, lb=LB, ub=UB).to(device)
            lf  = lambda w, m=mlp, d=data, b=beta: compute_losses_convection(m, d, b, w)
            ef  = lambda m=mlp, d=data, b=beta:    eval_convection(m, d, b)
            res = train(mlp, lf, ef, run_key=rk, checkpoint=checkpoint,
                        label=f'MLP beta={beta} aw={aw}', use_adaptive=aw)
            _save_weights(res, rk, checkpoint)
            sweep_rows.append(_summary_row(
                {'pde':'convection','model':'MLP','beta':beta,'grid_size':None,'adaptive':aw}, res))
            checkpoint.mark_done(rk, {'best_l2': res['best_l2'], 'n_params': res['n_params']})
            if beta == 30:
                _append_history(decomp_rows, res,
                    {'pde':'convection','model':'MLP','beta':beta,'grid_size':None,'adaptive':aw})
            _save(pd.DataFrame(sweep_rows),  'convection_beta_sweep.csv',  checkpoint)
            _save(pd.DataFrame(decomp_rows), 'convection_loss_decomp.csv', checkpoint)

        if not KAN_AVAILABLE:
            continue

        for gs in tqdm(KAN_GRIDS, desc=f'  KINN grid beta={beta}', leave=False, colour='cyan'):
            rk = make_run_key(pde='conv', model='KINN', beta=beta, gs=gs, aw=False)
            if checkpoint.is_done(rk):
                continue
            kan = KINN(2, KAN_HIDDEN_W, KAN_N_HIDDEN, gs, lb=LB, ub=UB).to(device)
            lf  = lambda w, m=kan, d=data, b=beta: compute_losses_convection(m, d, b, w)
            ef  = lambda m=kan, d=data, b=beta:    eval_convection(m, d, b)
            res = train(kan, lf, ef, run_key=rk, checkpoint=checkpoint,
                        label=f'KINN beta={beta} gs={gs}', use_adaptive=False)
            _save_weights(res, rk, checkpoint)
            heatmap_rows.append(_summary_row({'beta': beta, 'grid_size': gs}, res))
            sweep_rows.append(_summary_row(
                {'pde':'convection','model':'KINN','beta':beta,'grid_size':gs,'adaptive':False}, res))
            checkpoint.mark_done(rk, {'best_l2': res['best_l2'], 'n_params': res['n_params']})
            if beta == 30 and gs == 20:
                _append_history(decomp_rows, res,
                    {'pde':'convection','model':'KINN','beta':beta,'grid_size':gs,'adaptive':False})
            _save(pd.DataFrame(heatmap_rows), 'convection_heatmap.csv',    checkpoint)
            _save(pd.DataFrame(sweep_rows),   'convection_beta_sweep.csv', checkpoint)
            _save(pd.DataFrame(decomp_rows),  'convection_loss_decomp.csv',checkpoint)

        rk = make_run_key(pde='conv', model='KINN', beta=beta, gs=20, aw=True)
        if not checkpoint.is_done(rk):
            kan = KINN(2, KAN_HIDDEN_W, KAN_N_HIDDEN, 20, lb=LB, ub=UB).to(device)
            lf  = lambda w, m=kan, d=data, b=beta: compute_losses_convection(m, d, b, w)
            ef  = lambda m=kan, d=data, b=beta:    eval_convection(m, d, b)
            res = train(kan, lf, ef, run_key=rk, checkpoint=checkpoint,
                        label=f'KINN beta={beta} gs=20 aw=T', use_adaptive=True)
            _save_weights(res, rk, checkpoint)
            sweep_rows.append(_summary_row(
                {'pde':'convection','model':'KINN','beta':beta,'grid_size':20,'adaptive':True}, res))
            checkpoint.mark_done(rk, {'best_l2': res['best_l2'], 'n_params': res['n_params']})
            if beta == 30:
                _append_history(decomp_rows, res,
                    {'pde':'convection','model':'KINN','beta':beta,'grid_size':20,'adaptive':True})
            _save(pd.DataFrame(sweep_rows),   'convection_beta_sweep.csv', checkpoint)
            _save(pd.DataFrame(decomp_rows),  'convection_loss_decomp.csv',checkpoint)


def run_helmholtz(checkpoint):
    LB = [-1.,-1.]; UB = [1.,1.]; K = 1.
    sweep_rows = []; decomp_rows = []

    data_path = OUT / 'data_helmholtz.pt'
    data = _load_data(data_path)
    if data is None:
        data = make_helmholtz_data(seed=0)
        _save_data(data, data_path, checkpoint)

    mtypes = ['MLP'] + (['KINN'] if KAN_AVAILABLE else [])

    for n in tqdm(HELM_FREQS, desc='helmholtz n', colour='yellow'):
        for mtype in mtypes:
            for aw in [False, True]:
                for gs in ([10, 30] if mtype == 'KINN' else [None]):  # ← new loop
                    rk = make_run_key(pde='helm', model=mtype, n=n, aw=aw, gs=str(gs))
                    if checkpoint.is_done(rk):
                        continue

                    model = (
                        MLP(2, MLP_DEPTH, MLP_WIDTH, MLP_ACT, lb=LB, ub=UB)
                        if mtype == 'MLP'
                        else KINN(2, KAN_HIDDEN_W, KAN_N_HIDDEN, gs, lb=LB, ub=UB)
                    ).to(device)

                    lf = lambda w, m=model, d=data, n_=n: compute_losses_helmholtz(m, d, n_, K, w)
                    ef = lambda m=model, d=data, n_=n:    eval_helmholtz(m, d, n_)

                    res = train(model, lf, ef, run_key=rk, checkpoint=checkpoint,
                                label=f'{mtype} Helm n={n} gs={gs} aw={aw}',
                                use_adaptive=aw)

                    _save_weights(res, rk, checkpoint)
                    sweep_rows.append(_summary_row(
                        {'pde':'helmholtz','model':mtype,'n':n,'k':K,
                         'grid_size':gs,'adaptive':aw}, res))
                    checkpoint.mark_done(rk, {'best_l2': res['best_l2'],
                                              'n_params': res['n_params']})
                    if n == max(HELM_FREQS):
                        _append_history(decomp_rows, res,
                            {'pde':'helmholtz','model':mtype,'n':n,
                             'grid_size':gs,'adaptive':aw})
                    _save(pd.DataFrame(sweep_rows), 'helmholtz_freq_sweep.csv',  checkpoint)
                    _save(pd.DataFrame(decomp_rows),'helmholtz_loss_decomp.csv', checkpoint)


def run_poisson(checkpoint):
    LB = [0.]; UB = [1.]
    rows = []


    data_path = OUT / 'data_poisson.pt'
    data = _load_data(data_path)
    if data is None:
        data = make_poisson_data(seed=0)
        _save_data(data, data_path, checkpoint)

    mtypes = ['MLP'] + (['KINN'] if KAN_AVAILABLE else [])

    for mtype in tqdm(mtypes, desc='poisson model'):
        gs_list = [5, 10, 20] if mtype == 'KINN' else [None]
        for gs in tqdm(gs_list, desc=f'  {mtype} grid', leave=False):
            rk = make_run_key(pde='poisson', model=mtype, gs=str(gs))
            if checkpoint.is_done(rk):
                continue
            model = (MLP(1, MLP_DEPTH, MLP_WIDTH, MLP_ACT, lb=LB, ub=UB)
                     if mtype == 'MLP'
                     else KINN(1, KAN_HIDDEN_W, KAN_N_HIDDEN, gs, lb=LB, ub=UB)).to(device)
            lf = lambda w, m=model, d=data: compute_losses_poisson(m, d, w)
            ef = lambda m=model, d=data:    eval_poisson(m, d)
            res = train(model, lf, ef, run_key=rk, checkpoint=checkpoint,
                        label=f'{mtype} Poisson gs={gs}')
            _save_weights(res, rk, checkpoint)
            rows.append(_summary_row({'pde':'poisson','model':mtype,'grid_size':gs}, res))
            checkpoint.mark_done(rk, {'best_l2': res['best_l2'], 'n_params': res['n_params']})
            _save(pd.DataFrame(rows), 'poisson_validation.csv', checkpoint)


def run_param_efficiency(checkpoint, beta=30):
    LB = [0.,0.]; UB = [2*math.pi, 1.]
    rows = []; fname = f'param_efficiency_beta{int(beta)}.csv'


    data_path = OUT / 'data_convection.pt'
    data = _load_data(data_path)
    if data is None:
        data = make_convection_data(seed=0)
        _save_data(data, data_path, checkpoint)

    mlp_cfgs = [(3,32),(3,64),(4,64),(4,128),(5,128),(6,128)]
    for depth, width in tqdm(mlp_cfgs, desc='MLP param sweep'):
        rk = make_run_key(pde='peff', model='MLP', d=depth, w=width, beta=int(beta))
        if checkpoint.is_done(rk):
            continue
        model = MLP(2, depth, width, MLP_ACT, lb=LB, ub=UB).to(device)
        lf = lambda w_, m=model, d=data, b=beta: compute_losses_convection(m, d, b, w_)
        ef = lambda m=model, d=data, b=beta:     eval_convection(m, d, b)
        res = train(model, lf, ef, run_key=rk, checkpoint=checkpoint,
                    label=f'MLP d={depth} w={width}')
        _save_weights(res, rk, checkpoint)
        rows.append(_summary_row({'model':'MLP','depth':depth,'width':width,'grid_size':None}, res))
        checkpoint.mark_done(rk, {'best_l2': res['best_l2'], 'n_params': res['n_params']})
        _save(pd.DataFrame(rows), fname, checkpoint)

    if KAN_AVAILABLE:
        kan_cfgs = [(5,2,5),(5,2,10),(5,2,20),(5,2,50),
                    (5,3,5),(5,3,10),(10,2,10),(10,2,20)]
        for hw, nh, gs in tqdm(kan_cfgs, desc='KINN param sweep'):
            rk = make_run_key(pde='peff', model='KINN', hw=hw, nh=nh, gs=gs, beta=int(beta))
            if checkpoint.is_done(rk):
                continue
            model = KINN(2, hw, nh, gs, lb=LB, ub=UB).to(device)
            lf = lambda w_, m=model, d=data, b=beta: compute_losses_convection(m, d, b, w_)
            ef = lambda m=model, d=data, b=beta:     eval_convection(m, d, b)
            res = train(model, lf, ef, run_key=rk, checkpoint=checkpoint,
                        label=f'KINN hw={hw} nh={nh} gs={gs}')
            _save_weights(res, rk, checkpoint)
            rows.append(_summary_row({'model':'KINN','depth':nh+1,'width':hw,'grid_size':gs}, res))
            checkpoint.mark_done(rk, {'best_l2': res['best_l2'], 'n_params': res['n_params']})
            _save(pd.DataFrame(rows), fname, checkpoint)

checkpoint = DriveCheckpoint()

run_convection(checkpoint)

run_helmholtz(checkpoint)

run_poisson(checkpoint)

run_param_efficiency(checkpoint, beta = 30)

for beta in [1, 10, 50]:
    run_param_efficiency(checkpoint, beta=beta)